schema_version = "1.0.0"
id = "simple_camera_match"
version = "1.0.0"
name = "Simple Camera Match"
tagline = "Reconstruct camera perspective by drawing lines"
maintainer = "WittyMing"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Camera", "3D View"]
