schema_version = "1.0.0"
blender_version_min = "4.2.0"
version = "1.0.6"
id = "simple_camera_match"
name = "Simple Camera Match"
tagline = "Simple Camera Match - Blender插件"
license = ["SPDX:GPL-3.0-or-later"]
maintainer = "WittyMing"
type = "add-on"
website = "https://space.bilibili.com/27284213"
copyright = ["2026 WittyMing"]
tags = ["Object","3D View","Scene"]
platforms = ["windows-arm64","windows-x64","macos-arm64","macos-x64"]
